### ISSUE TITLE
Bad URL when downloading kong-oidc-<version>.rockspec from revomatico/kong

### ISSUE THREAD

**Issue by ebarped** [revomatico/docker-kong-oidc#23]
Hello!

The problem is that in the Dockerfile from every version, the url that uses kong-oidc-\<version\>.rockspec is pointing towards revomatico/kong-oidc master branch, causing download failures.

For example: (revomatico/docker-kong-oidc version 2.4.1-1 -> KONG_OIDC_VER=1.2.3-1)
Dockerfile: https://raw.githubusercontent.com/revomatico/docker-kong-oidc/2.4.1-1/Dockerfile

In the line 39, it tries to download from this URL:
`https://raw.githubusercontent.com/revomatico/kong-oidc/master/kong-oidc-${KONG_OIDC_VER}.rockspec`
This URL will transform with the env-var substitution into:
`https://raw.githubusercontent.com/revomatico/kong-oidc/master/kong-oidc-1.2.3-1.rockspec`

The issue is that, on the master branch of revomatico/kong-oidc, there is no kong-oidc-1.2.3-1.rockspec, because it has been updated and now is **kong-oidc-1.2.3-2.rockspec**

The solution will be to modify every dockerfile to point to the correct url of the revomatico/kong-oidc version. In this case, the correct url would be:
`https://raw.githubusercontent.com/revomatico/kong-oidc/v${KONG_OIDC_VER}/kong-oidc-${KONG_OIDC_VER}.rockspec`

Hope it helps!

**Comment by cristichiru** [comment]
You are absolutely right, thanks for pointing this out! Fixed for the 2.6.x release and for 2.5.x release. I do not see many reasons now to go too much back in time for this.
