### ISSUE TITLE
Facing oidc plugins issue

### ISSUE THREAD

**Issue by ShubhamShirbhate** [revomatico/docker-kong-oidc#24]
We trying oidc plugins through kong fill some configuration  like client id client secrets discovery etc
Aftr applying plugins, hit api url which is under the plugin they show no authorization header found 
Can any help us out your guidance is more helpful for me 

Thanks in advance

**Comment by cr1cr1** [comment]
I am sorry, but how can I help you if you do not provide any information like configs, logs, etc? Moreover, this place is not really suited for such support questions.
