### ISSUE TITLE
Got error when trying to hit the http://localhost:8000/mock (tag: 3.0.0-4)

### ISSUE THREAD

**Issue by diep-it-dn** [revomatico/docker-kong-oidc#34]
I got the same error as in this comment: [33](https://github.com/revomatico/docker-kong-oidc/issues/33#issuecomment-1250194915)
Could @cristichiru take a look? Thank you!

**Comment by cristichiru** [comment]
Indeed I left a piece of code in the plugin that I have now removed.

From https://docs.konghq.com/gateway/latest/plugin-development/custom-logic/#migrating-from-baseplugin-module:
```
You don’t need to add a :new() method or call any of the CustomHandler.super.XXX:(self) methods.
```

Try [3.0.0-5](https://github.com/revomatico/docker-kong-oidc/releases/tag/3.0.0-5)

**Comment by diep-it-dn** [comment]
Many thanks for the prompt reply!!!
I've tried to run on my localhost and also need to update the function [set_consumer(consumer, credential)](https://github.com/revomatico/kong-oidc/blob/master/kong/plugins/oidc/utils.lua#L95) up to date with [this from ldap-auth](https://github.com/Kong/kong/blob/master/kong/plugins/ldap-auth/access.lua#L161) to run successfully as in this snapshot:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/71241844/191213752-2430634a-5e46-411a-b64b-43496d8dd771.png">

if the warning "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'." is not related, I think it's fixed now!
