### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by jiangxuhui** [revomatico/docker-kong-oidc#36]
docker-kong-oidc version:2.6.0-2
when i do cmd:
```
docker build -t mykong:v1 .
```
![image](https://user-images.githubusercontent.com/28898668/205799521-5c63d271-d82d-472b-ba1d-c018f84ef5d1.png)

by the way, i do that command in arm computer.

**Comment by jiangxuhui** [comment]
![image](https://user-images.githubusercontent.com/28898668/205799939-7a7399e3-6f5e-43c7-958c-e7b7a1bd2dfe.png)

**Comment by cristichiru** [comment]
Seems to be a problem local to your machine since it cannot reach github.com

**Comment by jiangxuhui** [comment]
> Seems to be a problem local to your machine since it cannot reach github.com

sorry,i cannot agree.  my machine can connect github.com, my machine in Mumbai。

**Comment by cristichiru** [comment]
Actually, the error explicitly says it times out reading from github.com. Probably due to poor connection?

This is not a project bug, rather an issue with your build machine. I imagine you have already tried from other machines.

**Comment by cr1cr1** [comment]
No worries. I also hope you know there are [pre-built images already on docker hub](https://hub.docker.com/r/revomatico/docker-kong-oidc) so normally you don't need to build them yourself.

**Comment by jiangxuhui** [comment]
> No worries. I also hope you know there are [pre-built images already on docker hub](https://hub.docker.com/r/revomatico/docker-kong-oidc) so normally you don't need to build them yourself.

Ahaha，I need the image support ARM, so the image in dockerhub is no use for me. because it only support X86.
I have to build the image in arm machine by myself. thank dude.
