### ISSUE TITLE
How do I use this with Redis as a caching backend?

### ISSUE THREAD

**Issue by gboor** [revomatico/docker-kong-oidc#41]
I see that there's a bunch of configuration options in the image for memcached, shm, dshm, ... but nothing for Redis - at least not in the docs. How do I use this with Redis?

**Comment by cristichiru** [comment]
Currently is not implemented. I see https://github.com/bungle/lua-resty-session?tab=readme-ov-file#redis-configuration that has added Redis support. I am not really maintaining this anymore, so feel free to extend it and open a PR if you need Redis support.
