### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by neilscallywag** [revomatico/docker-kong-oidc#42]
Hi, is there documentation that I can refer to for a proper setup and usage?

**Comment by cristichiru** [comment]
Yes, 
- the main [README.md](https://github.com/revomatico/docker-kong-oidc) of this project
- https://github.com/revomatico/kong-oidc README
- and of course the existing [Kong documentation](https://docs.konghq.com/gateway/latest/production/kong-conf/). This release is basically Kong packaged with `kong-oidc` plugin and nothing more.

The way I use it: kubernetes deployment (using the Kong ingress controller) and overriding what I need in Kong deployment with environment variables.
