### ISSUE TITLE
Questions about kong-oidc version and docker 

### ISSUE THREAD

**Issue by phlegx** [revomatico/docker-kong-oidc#8]
Dear all,

we initially planned to use the https://github.com/nokia/kong-oidc plugin, but it seems to be outdated. Not sure if it even would work with `Kong 2.0`? What was the reason for your fork if I may ask?

I installed now your plugin https://github.com/revomatico/kong-oidc  simply via `luarocks` in the original `Kong` docker image and enabled it with:

```
KONG_PLUGINS=bundled,oidc
```

I do see it in `Konga` and try to enable and settling it up on a single route for testing

However I'm wondering: you created this custom Docker image here `docker-kong-oidc`. Do we need all steps/installations in your Dockerfile to make this plugin work? It seems to be a quite a lot of modifications to the original Kong image. Or are these simply some custom modifications that you need for yourself?

thanks a lot in advance

**Comment by cristichiru** [comment]
Hey there!

All those modifications are for the eventual use of different session mechanisms.

If you plan to go with the default (cookie), then just installing an updated version of the kong-oidc plugin should work just fine in a vanilla kong.

**Comment by cristichiru** [comment]
"just fine" assumes you also set larger header sizes in nginx/kong to accommodate fat session cookies (see https://github.com/revomatico/docker-kong-oidc#session-cookie)
